server:
  port: 8081

---

# 원본
# spring:
#   profiles: default
#   jpa:
#     properties:
#       hibernate:
#         show_sql: true
#         format_sql: true

spring:
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL57Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/petstore
    username: root
    password: admin
    driverClassName: com.mysql.cj.jdbc.Driver